version: '3.7'

services:
  app:
    build: .
    container_name: ultronx_bot
    env_file: ./env.list
    stdin_open: true
    tty: true
    ports:
      - "443:8443"
      # - "8080:8443"
    # map certs when using HTTPS
    volumes: 
      - /etc/letsencrypt/live/ultronx.mooo.com/privkey.pem:/src/ultronx/cert/privkey.pem
      - /etc/letsencrypt/live/ultronx.mooo.com/cert.pem:/src/ultronx/cert/cert.pem
      - /etc/letsencrypt/live/ultronx.mooo.com/chain.pem:/src/ultronx/cert/chain.pem
  

