version: "3.7"

services:
  bot:
    build: 
      context: ./bot
      dockerfile: ./Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        SLACK_BOT_ULTRON: ${SLACK_BOT_ULTRON}
        SLACK_CHANNEL_LIST: ${SLACK_CHANNEL_LIST}
        ULTRONEX_BOT_ID: ${ULTRONEX_BOT_ID}
        IRONMAN_USER_ID: ${IRONMAN_USER_ID}
        GIPHY_API_KEY: ${GIPHY_API_KEY}
        NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
        NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
        HTTP_SCHEME: ${HTTP_SCHEME}
        BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
        BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
        BASIC_AUTH_REALM: ${BASIC_AUTH_REALM}
        SECRET_WEAPON: ${SECRET_WEAPON}
        SENTRY_DSN: ${SENTRY_DSN}
    container_name: ultronex_bot
    stdin_open: true
    tty: true
    ports:
      - "443:8443"
    # map certs when using HTTPS
    volumes:
      - ./bot/app:/src/ultronex/app
      - ./bot/log:/src/ultronex/log
      - ./bot/tab:/src/ultronex/tab
      - /etc/letsencrypt/live/ultronex.mooo.com/privkey.pem:/src/ultronex/cert/privkey.pem
      - /etc/letsencrypt/live/ultronex.mooo.com/cert.pem:/src/ultronex/cert/cert.pem
      - /etc/letsencrypt/live/ultronex.mooo.com/chain.pem:/src/ultronex/cert/chain.pem
