version: "3.7"

services:
  ultronex:
    build:
      context: .
      dockerfile: ./Dockerfile-local
      args:
        ENV: ${ENV}
        SLACK_BOT_ULTRON: ${SLACK_BOT_ULTRON}
        SLACK_CHANNEL_LIST: ${SLACK_CHANNEL_LIST}
        ULTRONEX_BOT_ID: ${ULTRONEX_BOT_ID}
        IRONMAN_USER_ID: ${IRONMAN_USER_ID}
        GIPHY_API_KEY: ${GIPHY_API_KEY}
        NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
        NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
        HTTP_SCHEME: ${HTTP_SCHEME}
        BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
        BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
        BASIC_AUTH_REALM: ${BASIC_AUTH_REALM}
        SECRET_WEAPON: ${SECRET_WEAPON}
        SENTRY_DSN: ${SENTRY_DSN}
    container_name: ultronex_bot
    env_file:
      - ./env.list
    stdin_open: true
    tty: true
    expose:
      - 8443
    networks:
      ultronex:
        aliases:
          - ultronex_bot
    volumes:
      - ./app:/src/ultronex/app
      - ./log:/src/ultronex/log
      - ./tab:/src/ultronex/tab

  haproxy:
    build:
      context: .
      dockerfile: ./haproxy/Dockerfile
      args:
        HAPROXY_HTTP_SCHEME: ${HAPROXY_HTTP_SCHEME}
    container_name: ultronex_haproxy
    env_file:
      - ./haproxy/env.list
    networks:
      ultronex:
        aliases:
          - ultronex_haproxy
    ports:
      - "8080:80"
      - "18080:18080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - ultronex
networks:
  ultronex:
    driver: bridge
