version: '3.7'

services:
  app:
    build: .
    container_name: ultronex_bot
    env_file: ./env.list
    stdin_open: true
    tty: true
    ports:
      - "8080:8443"
    volumes: 
      - ./log:/src/ultronex/log

