version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile-local
    container_name: ultronex_bot
    env_file:
      - ./env.list
    stdin_open: true
    tty: true
    ports:
      - "8080:8443"
    volumes:
      - ./app:/src/ultronex/app
      - ./log:/src/ultronex/log
      - ./tab:/src/ultronex/tab
