version: "3.7"

services:
  bot:
    build:
      context: ./bot
      dockerfile: ./Dockerfile
      args:
        ENV: ${ENV}
        SLACK_BOT_ULTRON: ${SLACK_BOT_ULTRON}
        SLACK_CHANNEL_LIST: ${SLACK_CHANNEL_LIST}
        ULTRONEX_BOT_ID: ${ULTRONEX_BOT_ID}
        IRONMAN_USER_ID: ${IRONMAN_USER_ID}
        GIPHY_API_KEY: ${GIPHY_API_KEY}
        NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
        NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
        HTTP_SCHEME: ${HTTP_SCHEME}
        BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
        BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
        BASIC_AUTH_REALM: ${BASIC_AUTH_REALM}
        SECRET_WEAPON: ${SECRET_WEAPON}
        SENTRY_DSN: ${SENTRY_DSN}
    container_name: ultronex_bot
    env_file: ./bot/env.list
    stdin_open: true
    tty: true
    ports:
      - "8443:8443"
    networks:
      network:
        aliases:
          - ultronex_bot
    volumes:
      - ./bot/app:/src/ultronex/app
      - ./bot/log:/src/ultronex/log
      - ./bot/tab:/src/ultronex/tab
      - /etc/letsencrypt/live/ultronex.mooo.com/privkey.pem:/src/ultronex/cert/privkey.pem
      - /etc/letsencrypt/live/ultronex.mooo.com/cert.pem:/src/ultronex/cert/cert.pem
      - /etc/letsencrypt/live/ultronex.mooo.com/chain.pem:/src/ultronex/cert/chain.pem

  haproxy:
    build:
      context: ./haproxy
      dockerfile: ./Dockerfile
      args:
        HAPROXY_HTTP_SCHEME: ${HAPROXY_HTTP_SCHEME}
    container_name: ultronex_haproxy
    env_file:
      - ./haproxy/env.list
    networks:
      network:
        aliases:
          - ultronex_haproxy
    ports:
      - "80:80"
      - "443:443"
      - "18443:18443"
      - "18888:18888"
      - "8040:8040"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt/live/ultronx.mooo.com:/etc/letsencrypt/live/ultronx.mooo.com
      - /etc/letsencrypt/live/ultronex.mooo.com/haproxy.pem:/etc/ssl/cert/haproxy.pem
      - /.well-known/acme-challenge:/.well-known/acme-challenge
    links:
      - bot

  scope:
    image: weaveworks/scope:latest
    container_name: ultronex_scope
    env_file:
      - ./scope/env.list
    networks:
      network:
        aliases:
          - ultronex_scope
    ports:
      - "4040:4040"
    pid: "host"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"

networks:
  network:
    driver: bridge
