#!/bin/bash
certbot renew --tls-sni-01-port=8888
cat /etc/letsencrypt/live/ultronex.mooo.com/fullchain.pem /etc/letsencrypt/live/ultronex.mooo.com/privkey.pem > /etc/letsencrypt/live/ultronex.mooo.com/haproxy.pem