FROM elixir:1.10.2-slim AS base

RUN apt-get -qq update && \
    apt-get -qq -y install build-essential --fix-missing --no-install-recommends


ENV PROJECT_ROOT /src/ultronex

ENV PATH ${PROJECT_ROOT}/bin:$PATH

WORKDIR ${PROJECT_ROOT}

COPY . .

# Install Hex+Rebar
RUN mix local.hex --force && \
    mix local.rebar --force

RUN MIX_ENV=prod mix deps.get && \
    MIX_ENV=prod mix deps.compile

ARG ENVIRONMENT
ARG SLACK_BOT_ULTRON
ARG SLACK_CHANNEL_LIST
ARG ULTRONEX_BOT_ID
ARG IRONMAN_USER_ID
ARG GIPHY_API_KEY
ARG HTTP_SCHEME
ARG BASIC_AUTH_USERNAME
ARG BASIC_AUTH_PASSWORD
ARG BASIC_AUTH_REALM
ARG SECRET_WEAPON
ARG SENTRY_DSN
ARG APPSIGNAL_PUSH_API_KEY

ENV ENVIRONMENT=${ENVIRONMENT}
ENV SLACK_BOT_ULTRON=${SLACK_BOT_ULTRON}
ENV SLACK_CHANNEL_LIST=${SLACK_CHANNEL_LIST}
ENV ULTRONEX_BOT_ID=${ULTRONEX_BOT_ID}
ENV IRONMAN_USER_ID=${IRONMAN_USER_ID}
ENV GIPHY_API_KEY=${GIPHY_API_KEY}
ENV HTTP_SCHEME=${HTTP_SCHEME}
ENV BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}
ENV BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
ENV BASIC_AUTH_REALM=${BASIC_AUTH_REALM}
ENV SECRET_WEAPON=${SECRET_WEAPON}
ENV SENTRY_DSN=${SENTRY_DSN}
ENV APPSIGNAL_PUSH_API_KEY=${APPSIGNAL_PUSH_API_KEY}

RUN MIX_ENV=prod mix compile 
RUN MIX_ENV=prod mix release

LABEL maintainer="ahsan.dar@live.com"

ARG BUILD_DATE
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.build-date=$BUILD_DATE
LABEL org.label-schema.name="ahsan/ultronex"
LABEL org.label-schema.description="Slack Bot - ULTRONX"
LABEL org.label-schema.url="https://github.com/ahsan/ultronex"


EXPOSE 8443

ENTRYPOINT ["_build/prod/rel/ultronex/bin/ultronex", "start"]
